name: Check Package CGManifests

on:
  push:
    branches: [ main, dev, 1.0* ]
  pull_request:
    branches: [ main, dev, 1.0* ]

jobs:

  build:
    name: Validate Manifests
    runs-on: ubuntu-18.04
    steps:
    
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get the changed spec files for PRs
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        git fetch origin ${{ github.base_ref }}
        base_sha=$(git rev-parse origin/${{ github.base_ref }})
        echo "Merging ${{ github.sha }} into ${{ github.base_ref }}"
        echo "Files changed: '$(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }})'"
        changed_specs=$(git diff-tree --no-commit-id --name-only -r $base_sha ${{ github.sha }} | { grep "\.spec$" || test $? = 1; })
        echo "Files to validate: '${changed_specs}'"
        echo "specs-to-check=$(echo "${changed_specs}")" >> $GITHUB_ENV
        
    - name: Get all spec files for Pushes
      if: ${{ github.event_name == 'push' }}
      run: |
        all_specs=$( find . -name "*.spec" )
        echo "specs-to-check=$(echo "${all_specs}")" >> $GITHUB_ENV

    - name: Run the validation check
      run: |
        .github/workflows/validate-cg-manifest.sh ${{ env.specs-to-check }}
